services:
  postgres:
    image: postgres:16-alpine
    container_name: kanbanice-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: kanbanice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pilot7736

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: