-- H2-compatible schema for testing (PostgreSQL Mode)

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS project_member;
DROP TABLE IF EXISTS kanban_task;
DROP TABLE IF EXISTS kanban_board;
DROP TABLE IF EXISTS kanban_project;
DROP TABLE IF EXISTS app_user;
DROP TABLE IF EXISTS company;

CREATE TABLE company (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE app_user (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        VARCHAR(255) NOT NULL,
    username                    VARCHAR(255) NOT NULL UNIQUE,
    email                       VARCHAR(255) UNIQUE,
    password                    VARCHAR(255) NOT NULL,
    user_type                   VARCHAR(20),
    provider_type               VARCHAR(20) NOT NULL,
    provider_id                 VARCHAR(255),
    reset_token                 VARCHAR(255),
    reset_token_expiry          TIMESTAMP,
    last_password_reset_request TIMESTAMP,
    pending_email               VARCHAR(255),
    email_verification_token    VARCHAR(255),
    email_verification_expiry   TIMESTAMP,
    company_id                  BIGINT REFERENCES company(id) ON DELETE SET NULL
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    roles   VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, roles)
);

CREATE TABLE kanban_project (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    company_id BIGINT NOT NULL REFERENCES company(id) ON DELETE CASCADE,
    created_at TIMESTAMP
);

CREATE TABLE project_member (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES kanban_project(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    role       VARCHAR(20) NOT NULL,
    CONSTRAINT uq_project_member UNIQUE (project_id, user_id)
);

CREATE TABLE kanban_board (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    project_id BIGINT NOT NULL REFERENCES kanban_project(id) ON DELETE CASCADE,
    created_at TIMESTAMP
);

CREATE TABLE kanban_task (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(255) NOT NULL,
    description       VARCHAR(4000),
    status            VARCHAR(20) NOT NULL DEFAULT 'TODO',
    status_changed_by VARCHAR(255),
    board_id          BIGINT NOT NULL REFERENCES kanban_board(id) ON DELETE CASCADE,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP
);